# Generated by Django 5.1.5 on 2025-01-27 08:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0004_alter_appeal_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=50, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='available_balance',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='sponsor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'sponsor'}, on_delete=django.db.models.deletion.PROTECT, related_name='appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('reviewing...', 'Reviewing...'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
